version: "2.0"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   
  django:
    image: adriangameromedina/centro_comercial:latest
    ports:
      - "8000:8000"
